spring.application.name=PingCortex

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pingcortex}
spring.datasource.username=${DB_USER:pingcortex}
spring.datasource.password=${DB_PASSWORD:pingcortex}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000